name: ww

on:
  workflow_dispatch:
  push:
    paths:
    - '.github/workflows/ww.yml'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v6
    - uses: mlugg/setup-zig@v2
    - name: Cache
      uses: actions/cache@v5
      with:
        path: zigrika
        key: zigrika
    - name: Build
      run: |
        if (Test-Path "zigrika") {
          echo 'update repo'
          cd zigrika
          git pull
          cd ..
        } else {
          echo 'clone repo'
          git clone https://git.xeondev.com/WavyRooms/zigrika
        }
        cp -r zigrika build
        cd build
        zig build -Doptimize=ReleaseSmall
        mv zig-out/bin/*.exe ./
        7z a ..\zigrika.7z assets\ state\ *.exe
    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: zigrika.7z
        tag: 3.6beta
        overwrite: true
        file_glob: true
